remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Mike Huffmaster]
description: [My journey from construction to computer science.  I will track my journey and the steps I take to branch into the technology field.  I will showcase my projects, resume, and blog my journey.]
